# Generated by Django 5.2 on 2025-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quizattempt_quiz_remove_quizattempt_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject of the quiz (e.g., Math, Science)', max_length=100),
        ),
    ]
