# Generated by Django 5.2 on 2025-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio_customuser_branch_customuser_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
