# Generated by Django 5.2 on 2025-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admininvitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sub_admin',
            field=models.BooleanField(default=False),
        ),
    ]
